---
title: "CS_11"
author: "Yue Ma"
date: "11/16/2022"
output: github_document
---

```{r}
library(tidyverse)
library(spData)
library(sf)

## New Packages
library(mapview) # new package that makes easy leaflet maps
library(foreach)
library(doParallel)
registerDoParallel(4)
getDoParWorkers() # check registered cores
```

# use API key

```{r}
library(tidycensus)
census_api_key("05670ba5a977c8507163268643ea67909e32759c",install = TRUE, overwrite = TRUE)
```

# download the data


```{r}
library(tidycensus)
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=TRUE) 
```
# parallel computing
```{r}
buffalo <- erie %>% 
   st_crop(c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92))



buffalo_dots=
   foreach(r=unique(buffalo$variable),.combine=rbind)%dopar%{
   filter(buffalo,variable==r) %>%  #do one variable at a time
   st_sample(size=.$value) %>%  #generate a point for each person randomly
   st_as_sf() %>%  #convert to a full sf object
   mutate(variable=r) #add the variable onto the points
   }
```

```{r, message=FALSE, warning = FALSE}
mapview(buffalo_dots, zcol = "variable",cex = 0.01,alpha = 0)
```
